service: kotlin-graalvm-http4k-demo

provider:
  name: aws
  runtime: java11
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["myTable", "Arn" ] }

package:
  artifact: output/lambda.zip

resources:
  Resources:
    myTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test-http4k
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  test-graalvm-get:
    handler: not.used
    runtime: provided
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /json
          method: GET
      - http:
          path: /json-post
          method: POST