name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: fwilhe2/setup-kotlin@main
      - name: build project
        run: ./gradlew shadowJar
      - name: docker build native
        run: docker run -v $(pwd):/source \
    http4k/amazonlinux-java-graal-ce-lambda-runtime:latest \
    build/libs/*.jar \
    HelloHttp4kGraal.zip
